### ISSUE TITLE
As an admin, I want to be able to edit an invoice so that I can correct any mistakes.

### ISSUE THREAD

**Issue by JohnoAlm** [KYH-Net23/AdminInvoiceService#4]
# Acceptance Criteria:

- [ ] The admin should be able to modify key details such as
- [ ] All fields have validation to prevent invalid entries.
- [ ] There should be “save” and “cancel” buttons.
- [ ] When pressing “save” or “cancel”, a confirmation prompt should appear, asking the admin to confirm before continuing.
- [ ] The change should be added to a log.

# Tasks:

# Test Cases:

# Activity Diagram
